8241712: AArch64: TestDowncall fails with IllegalArgumentException: No ABI attribute present
Tests cases where the structure has an initial floating point element
followed by padding fail with this exception. The padding element
doesn't have the NATIVE_TYPE attribute.

  test TestDowncall.testDowncall("f0_V_S_FD", VOID, [STRUCT], [FLOAT, DOUBLE]): failure
  java.lang.IllegalArgumentException: No ABI attribute present
          at jdk.incubator.foreign/jdk.incubator.foreign.SystemABI$Type.lambda$fromLayout$0(SystemABI.java:195)
          at java.base/java.util.Optional.orElseThrow(Optional.java:401)
          at jdk.incubator.foreign/jdk.incubator.foreign.SystemABI$Type.fromLayout(SystemABI.java:195)
          at jdk.incubator.foreign/jdk.internal.foreign.abi.aarch64.CallArranger.isHomogeneousFloatAggregate(CallArranger.java:207)
          at jdk.incubator.foreign/jdk.internal.foreign.abi.aarch64.CallArranger.classifyStructType(CallArranger.java:220)

Change-Id: Id7dcda45e604f4d8e928dfe094a021cca74af741